image: "python:3.8"

pages:
  stage: deploy
  script:
    - pip install .
    - mdslides main/presentation.md --include main/media
    - mv presentation public
  artifacts:
    paths:
      - public
  only:
    - master
variables:
  GIT_SUBMODULE_STRATEGY: recursive
